web:
  build: .
  command: "/env/bin/python manage.py runserver 0.0.0.0:8000"
  environment:
    DJANGO_SETTINGS_MODULE: ballotify.settings.prod
    SECRET_KEY: oQiLwk7pMXronMdxbyComCzbD9MtYtF6FBF9UaywbTjVDqojEACyAcnN
  volumes:
    - .:/app
  ports:
   - "8002:8000"
  links:
   - db
db:
  image: postgres:9.4.1
  environment:
    DATABASE_NAME: ballotify
    POSTGRES_USER: rambo
    POSTGRES_PASSWORD: z8CtmFNeywnexxBYh3rGXGsNjDgF
    PGPASSWORD: z8CtmFNeywnexxBYh3rGXGsNjDgF
